### ISSUE TITLE
The icons doesn't show

### ISSUE THREAD

**Issue by flopezre** [moser-jose/mosmmy-icons-vscode#1]
Hello, so the icons doesn't show:
![zdczxc](https://user-images.githubusercontent.com/4932575/112422904-677a6600-8d10-11eb-893b-4ab4ba2519f5.PNG)

Los iconos no se muestran todos, solo algunos.

Saludos

**Comment by flopezre** [comment]
Up

**Comment by moser-jose** [comment]
Olá já estão actualizados na versão recente. thanks

**Comment by flopezre** [comment]
Gracias Moser, ¿puedes agregar un icono para Nodemon?
![nodemon](https://user-images.githubusercontent.com/4932575/220796531-207eaad8-7f80-4507-b342-20cc16e3f5c4.png)

Saludos.

**Comment by moser-jose** [comment]
olá @flopezre  já foi adicionado, posdes actulizar pra nova versão, gracias

**Comment by flopezre** [comment]
Hola Moser, yo otra vez 😅, faltan iconos para las rutas en TypeScript y para el tsconfig.json
![asdfasd](https://user-images.githubusercontent.com/122753033/221334307-68336983-1be5-4b84-9244-f39f1cc993b5.png)

Como los de Material Icon;

![asasd](https://user-images.githubusercontent.com/4932575/221334480-34e01318-a6b0-4bd8-aed7-4d5b9dedc43f.png)

Saludos.

**Comment by moser-jose** [comment]
Hola, decidí cambiar los iconos de TypeScript con extensión .ts, y también algunos de configuración, pero no iguales a los iconos de Material Icon

Ya está en la versión más reciente, puedes actualizar.

Gracias

**Comment by flopezre** [comment]
Hola 😅, ¿podrias agregar iconos para Spring boot?

![asdasd](https://user-images.githubusercontent.com/4932575/221743557-f35a1fa7-a71e-4ee3-9d1f-8ed66780feb3.png)

Saludos. perdon :(

**Comment by moser-jose** [comment]
Holla @flopezre já pode actualizar

**Comment by FabianLoRs** [comment]
Hola @moser-jose,😅 tengo mas peticiones de iconos para estas carpetas:

![folder_icons](https://user-images.githubusercontent.com/122753033/229952480-a7b43def-0e66-4c84-a60c-ab0bf6167e86.png)

**Comment by moser-jose** [comment]
Hola @FabianLoRs pode actualizar 💯 v1.0.6

**Comment by FabianLoRs** [comment]
Iconos perdidos :c

![fdsfd](https://user-images.githubusercontent.com/122753033/230154739-1e7f4f12-00ee-4f8e-95c8-b4d89dcb2fcc.png)

**Comment by moser-jose** [comment]
desculpas, já foi corrigido v1.0.7

**Comment by FabianLoRs** [comment]
Hola, hay un error con la carpeta features y mas iconos para middlewares, redis, queues, endpoints, shareds, globals, http and generators.
![Animation_02](https://user-images.githubusercontent.com/122753033/231655015-1f020240-b87b-4d5e-8376-330bb5f1bee4.gif)

Saludos ✌

**Comment by FabianLoRs** [comment]
Y utilities y .http para Rest Client 🙏:

![98496](https://user-images.githubusercontent.com/122753033/232345044-6b249b02-22c0-433c-b690-5fbcb2dcc085.png)

Mas emails:

![646741](https://user-images.githubusercontent.com/122753033/233254101-b2f51dff-0b93-4923-a938-0bff05ee12e4.png)

**Comment by FabianLoRs** [comment]
.ejs

![6156g1fg](https://user-images.githubusercontent.com/122753033/234707687-ed5da5ea-543d-4897-b682-e05806844825.png)

**Comment by moser-jose** [comment]
@FabianLoRs  actualize v1.0.9

**Comment by FabianLoRs** [comment]
Hello Moser me again 😅, Is it possible to add more file icons for the folders in a Spring projects?

![folders](https://github.com/moser-jose/mosmmy-icons-vscode/assets/122753033/daab3602-1926-4408-802c-afe7b008de50)
