### ISSUE TITLE
Request for New File Icons

### ISSUE THREAD

**Issue by arv-anshul** [moser-jose/mosmmy-icons-vscode#2]
As a Python developer using your custom file icons extension in Visual Studio Code, I've noticed some missing icons that hinder my workflow. Adding these icons would significantly improve usability:

1. **`core/` Directory Icon:** Helps identify essential project modules.
2. **`__init__.py` Icon:** Distinguishes Python package initializer.
3. **`.streamlit/` Directory Icon:** Aids Streamlit developers in managing configs.
4. **`requirements.txt` Icon:** Facilitates quick identification of dependency files.

**Rationale:**

These icons would boost productivity by simplifying file and directory identification. They are crucial for Python developers in VSCode.

**Proposed Solution:**

Please consider adding these icons to enhance the Python development experience with your extension.

Thank you for your attention.

**Comment by moser-jose** [comment]
Thank you for your feedback; we will quickly include these icons. 

Could you please send a picture of the icons for the files and folders in your project? because `__init__.py` file is already supported.

**Comment by arv-anshul** [comment]
I can just send you the references for the file icons.

For, `__init__.py` file just create a difference between normal python script and `__init__.py` file. I noticed this in another file icon theme on VS-Code marketplace [here](https://marketplace.visualstudio.com/items?itemName=tal7aouy.icons).

| Name | Icon |
| ---: | :---: |
|`requirements.txt`| ![image](https://github.com/moser-jose/mosmmy-icons-vscode/assets/111767754/c4708d85-0f10-48a9-b2e9-2cda8f0e6e77) |
| `core/` | ![image](https://github.com/moser-jose/mosmmy-icons-vscode/assets/111767754/8f4d7f2d-fd2e-4d49-bd32-5320c7a0d90a) |
| `__init__.py` | ![image](https://github.com/moser-jose/mosmmy-icons-vscode/assets/111767754/56f5ee49-064f-4f9b-bcda-52db7f9c59f3) |
| `.streamlit/` | ![image](https://github.com/moser-jose/mosmmy-icons-vscode/assets/111767754/73c0e647-6410-4da2-a178-07d1eae720ed) |

> **Note:** All the icons provided above are just for reference and inspiration.

**Thank You to consider me.**

**Comment by arv-anshul** [comment]
Issue Resolved.
